In [ ]:
%pip install tensorflow pandas numpy matplotlib scikit-learn

In [9]:
import pandas as pd  
import numpy as np 
import matplotlib.pyplot as plt

In [10]:
ds = pd.read_csv("dataset.csv")
ds.head()

Marital status  Application mode  Application order  Course  \
0               1                 8                  5       2   
1               1                 6                  1      11   
2               1                 1                  5       5   
3               1                 8                  2      15   
4               2                12                  1       3   

   Daytime/evening attendance  Previous qualification  Nacionality  \
0                           1                       1            1   
1                           1                       1            1   
2                           1                       1            1   
3                           1                       1            1   
4                           0                       1            1   

   Mother's qualification  Father's qualification  Mother's occupation  ...  \
0                      13                      10                    6  ...   
1                       1                       3                    4  ...   
2                      22                      27                   10  ...   
3                      23                      27                    6  ...   
4                      22                      28                   10  ...   

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    0   
1                                    0                                    6   
2                                    0                                    6   
3                                    0                                    6   
4                                    0                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       0   
1                                       6   
2                                       0   
3                                      10   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000   
1                                    6                         13.666667   
2                                    0                          0.000000   
3                                    5                         12.400000   
4                                    6                         13.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               10.8   
1                                               0               13.9   
2                                               0               10.8   
3                                               0                9.4   
4                                               0               13.9   

   Inflation rate   GDP    Target  
0             1.4  1.74   Dropout  
1            -0.3  0.79  Graduate  
2             1.4  1.74   Dropout  
3            -0.8 -3.12  Graduate  
4            -0.3  0.79  Graduate  

[5 rows x 35 columns]

In [11]:
X = ds.iloc[:,:-1].values
X

array([[ 1.  ,  8.  ,  5.  , ..., 10.8 ,  1.4 ,  1.74],
       [ 1.  ,  6.  ,  1.  , ..., 13.9 , -0.3 ,  0.79],
       [ 1.  ,  1.  ,  5.  , ..., 10.8 ,  1.4 ,  1.74],
       ...,
       [ 1.  ,  1.  ,  1.  , ..., 13.9 , -0.3 ,  0.79],
       [ 1.  ,  1.  ,  1.  , ...,  9.4 , -0.8 , -3.12],
       [ 1.  ,  5.  ,  1.  , ..., 12.7 ,  3.7 , -1.7 ]])

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[-0.29482875,  0.21006857,  2.49089589, ..., -0.28763846,
         0.12438647,  0.76576084],
       [-0.29482875, -0.16740639, -0.55406775, ...,  0.87622207,
        -1.10522155,  0.34719942],
       [-0.29482875, -1.11109377,  2.49089589, ..., -0.28763846,
         0.12438647,  0.76576084],
       ...,
       [-0.29482875, -1.11109377, -0.55406775, ...,  0.87622207,
        -1.10522155,  0.34719942],
       [-0.29482875, -1.11109377, -0.55406775, ..., -0.81325289,
        -1.46687097, -1.37551124],
       [-0.29482875, -0.35614386, -0.55406775, ...,  0.42569541,
         1.7879738 , -0.74987207]])

In [13]:
y = ds.iloc[:,-1].values
y

array(['Dropout', 'Graduate', 'Dropout', ..., 'Dropout', 'Graduate',
       'Graduate'], dtype=object)

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=0)

In [15]:
from tensorflow.keras import regularizers
import tensorflow as tf
# Initialising ANN
ann = tf.keras.models.Sequential()

# Adding layers

ann.add(tf.keras.layers.Dense(units=64, activation='relu'))
ann.add(tf.keras.layers.Dropout(0.2))
ann.add(tf.keras.layers.Dense(units=32, activation='relu'))
ann.add(tf.keras.layers.Dropout(0.2))
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))  # Use softmax for multi-class classification

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y_train_int = label_encoder.fit_transform(y_train)
y_test_int = label_encoder.transform(y_test)
ann.compile(optimizer='adam',
            loss='sparse_categorical_crossentropy',  # For integer-encoded labels
            metrics=['accuracy'])
ann.fit(X_train,y_train_int,batch_size = 32,epochs=50)

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
y_pred_prob = ann.predict(X_test)
y_pred_ANN = np.argmax(y_pred_prob, axis=1)

14/14 [==============================] - 0s 383us/step


In [29]:
acc_ANN = accuracy_score(y_test_int,y_pred_ANN)
print(f"Accuracy of ANN is {acc_ANN}")

Accuracy of ANN is 0.7878103837471784


In [33]:
X_train[0]

array([ 4.65829423,  0.96501847, -0.55406775,  1.6394177 , -2.8564699 ,
       -0.38640411, -0.14558608,  1.07231532,  0.9548338 ,  0.67098721,
        0.4490872 , -1.10191389, -0.10799294, -0.358167  ,  0.36813532,
       -0.73657203, -0.57491418,  0.8876885 , -0.15968211, -0.30081306,
       -0.51234756,  0.40705879, -0.55160375,  0.00533646, -0.19927303,
       -0.28244231, -0.5611611 , -0.0160332 ,  0.18716526,  0.0325887 ,
       -0.19944099,  0.42569541,  1.7879738 , -0.74987207])

In [35]:
import numpy as np

# Function to predict the class for a new input (student's parameters)
def predict_student_class(input_data):
    # input_data should be a list or array of features corresponding to the model's input
    # Example: [feature1, feature2, feature3, ...]

    # Scale the input data using the same scaler that was used for training
    input_data_scaled = sc.transform([input_data])  # The input_data should be a 2D array

    # Predict the probabilities for each class
    y_pred_prob_individual = ann.predict(input_data_scaled)

    # Get the class with the highest probability
    predicted_class = np.argmax(y_pred_prob_individual, axis=1)

    # Decode the class label from integer to string (if needed)
    predicted_class_label = label_encoder.inverse_transform(predicted_class)

    return predicted_class_label[0]  # Returns the predicted label (e.g., 'Class1', 'Class2', 'Class3')

# Example usage
# Assume you have the student's parameters as a list or numpy array, for example:
new_student_input = X_train[100]  # Example input features

# Get the predicted class for this student
predicted_class = predict_student_class(new_student_input)

print(f"The predicted class for the student is: {predicted_class}")

1/1 [==============================] - 0s 12ms/step
The predicted class for the student is: Dropout


In [36]:
# Save the model in the current directory as 'student_classification_model.h5'
ann.save('student_classification_model.h5')

print("Model saved as 'student_classification_model.h5' in the current directory.")

Model saved as 'student_classification_model.h5' in the current directory.


/Users/girish/.pyenv/versions/3.8.18/lib/python3.8/site-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [37]:
import joblib
from sklearn.preprocessing import StandardScaler

# Assuming 'X_train' is your training data
scaler = StandardScaler()
scaler.fit(X_train)  # Fit the scaler on the training data

# Save the fitted scaler to a file
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']